/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Custom Block Shape",
  "description": "Adjust the padding, corner radius, and notch height of blocks to your preference..",
  "tags": [
    "theme"
  ],
  "credits": [
    {
      "name": "SheepTester",
      "link": "https://scratch.mit.edu/users/Sheep_maker/"
    },
    {
      "name": "lisa_wolfgang",
      "link": "https://scratch.mit.edu/users/lisa_wolfgang/"
    },
       {
      "name": "-Charcoal_Afterlife-",
      "link": "https://scratch.mit.edu/users/-Charcoal_Afterlife-/
    },
    {
      "name": "GarboMuffin",
      "link": "https://scratch.mit.edu/users/GarboMuffin/"
    }
  ],
  "enabledByDefault": false,
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "info": [
    {
      "type": "notice",
      "text": "Decreasing the padding size is only visible to you, so when your projects are viewed by other users, your scripts may overlap.",
      "id": "paddingWarning"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Padding size (0 - 550%)",
      "id": "paddingSize",
      "type": "integer",
      "min": 0,
      "default": 85,
      "max": 550
    },
    {
      "dynamic": true,
      "name": "Corner size (0 to 550%)",
      "id": "cornerSize",
      "type": "integer",
      "min": 0,
      "default": 110,
      "max": 550
    },
    {
      "dynamic": true,
      "name": "Notch height (0 - 550%)",
      "id": "notchSize",
      "type": "integer",
      "min": 0,
      "default": 125,
      "max": 550
    }
  ],
  "presets": [
    {
      "name": "3.0 Blocks",
      "id": "default3",
      "description": "The regular appearance of Scratch 3.0 blocks",
      "values": {
        "paddingSize": 100,
        "cornerSize": 100,
        "notchSize": 100
      }
    },
    {
      "name": "2.0 Blocks",
      "id": "default2",
      "description": "An appearance similar to Scratch 2.0 blocks",
      "values": {
        "paddingSize": 70,
        "cornerSize": 150,
        "notchSize": 75
      }
    },
          {
      "name": "2.0 Flat",
      "id": "default2",
      "description": "An appearance similar to Scratch 2.0 blocks with notches and corners removed.",
      "values": {
        "paddingSize": 70,
        "cornerSize": 0,
        "notchSize": 0
      }
    },
    {
      "name": "3.0 Flat",
      "id": "flat3",
      "description": "Scratch 3.0 blocks with notches and corners removed",
      "values": {
        "paddingSize": 100,
        "cornerSize": 0,
        "notchSize": 0
      }
    },
          {
      "name": "Puzzle3",
      "id": "puz3",
      "description": "Scratch 3.0 blocks with corners removed",
      "values": {
        "paddingSize": 100,
        "cornerSize": 0,
        "notchSize": 100
      }
    },
                {
      "name": "Puzzle2",
      "id": "puz2",
      "description": "Scratch 2.0 blocks with corners removed",
      "values": {
        "paddingSize": 70,
        "cornerSize": 0,
        "notchSize": 100
      }
    },
    {
      "name": "2.0 Flat",
      "id": "flat2",
      "description": "Scratch 2.0 blocks with notches and corners removed",
      "values": {
        "paddingSize": 70,
        "cornerSize": 0,
        "notchSize": 0
      }
    },
          {
      "name": "FalconMod Default",
      "id": "flat2",
      "description": "The Default Block Shape for FalconMod.",
      "values": {
        "paddingSize": 85,
        "cornerSize": 110,
        "notchSize": 125
      }
    }
  ]
};
export default manifest;
